### ISSUE TITLE
Login with bad credentials Error: POST http://localhost:3000/login 401 (Unauthorized)

### ISSUE THREAD

**Issue by haydenwade** [haydenty/Plateo#15]
When invalid credentials are entered at login it returns this error in the debug console even though I handle the error. Is this expected? If not how do you go about fixing it...

**Please work off of the Hacktoberfest branch and make all PR to that branch, thanks!**

**Comment by AlexITC** [comment]
This is not an application issue but a browser feature, in my case, Firefox detects the server error (401) as a network error, you can disable this behavior turning off 'network errors' in the console.

See the following screenshot, interpret 'Errores' as 'Errors' and 'Red' as 'Network'.
<img width="537" alt="screen shot 2016-10-02 at 10 44 02 pm" src="https://cloud.githubusercontent.com/assets/4218436/19026993/c838e7aa-88f1-11e6-8f9d-8d123121b1a1.png">

**Comment by haydenwade** [comment]
@AlexITC  thanks for the info, I'll have to play around with my browser settings thanks!
