### ISSUE TITLE
On page reload AuthenticationFactory.user gets set to undefined

### ISSUE THREAD

**Issue by haydenwade** [haydenty/Plateo#16]
AuthenticationFactory.user gets set on login (login.js line 25) and then in auth.factory.js line 8 gets set again on page reload. I can't seem to track down what happens to it. Not sure if I am not retrieving it from localStorage correctly (seemed to work for other data I store in localStorage)

Steps to reproduce: (after you fork the repo)
1. npm install
2. bower install
3. node server
4. navigate to localhost:3000
5. register a user (firstname: test, lastname: test, password: test123, email: test@test.com, username:test)
6. Go to **My Plates** tab (look at terminal session you will see something close to the following)
![image](https://cloud.githubusercontent.com/assets/9388749/19026352/60f02cf4-88ea-11e6-9e58-998618b06ef5.png)
1. Refresh the page (you will see this in the terminal)
   ![image](https://cloud.githubusercontent.com/assets/9388749/19026358/8252bccc-88ea-11e6-9e7d-43525000cd82.png)

**Please work off of the Hacktoberfest branch and make all PR to that branch, thanks!**

**Comment by AlexITC** [comment]
I had upload a pull request for fixing the issue, it was due to storing the user as object in local storage (which allow strings only).
