### ISSUE TITLE
Validation for Registration Page is not correct

### ISSUE THREAD

**Issue by haydenwade** [haydenty/Plateo#2]
This is when a user does not satisfy the requirements that is needed to create an account 
ex: password is too short, must contain etc. (might have to look at server to find out what the requirements are) 

does work for some validation rules.

**Please work off of the Hacktoberfest branch and make all PR to that branch, thanks!**

**Comment by AlexITC** [comment]
I had uploaded a pull request to validate that a password meets the following requirements  (based on the source code):
- contains at least 1 upper case letter
- contains at least 1 lower case letter
- contains at least 1 special character

**Comment by haydenwade** [comment]
@AlexITC thanks for all your contributions to my project, really appreciate it. The knowledge transfer is must quicker and more ingrained here rather than reading forums online. Thanks again, Happy coding!
