### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by haydenwade** [haydenty/Plateo#4]
simple but memorable

**Comment by naugle92** [comment]
Where at?

**Comment by oles** [comment]
Pull request for this at https://github.com/haydenty/Plateo/pull/5 :+1:

**Comment by haydenwade** [comment]
@naugle92 main index.html, check out what @oles did in PR #5
@oles initial look at this looks good, I'll take a better peek at it when I get back online. Thanks!
