### ISSUE TITLE
Missing Assets Directory 

### ISSUE THREAD

**Issue by haydenwade** [haydenty/Plateo#9]
![image](https://cloud.githubusercontent.com/assets/9388749/19009924/b3cb7d3c-873e-11e6-95c2-43464915d5da.png)

TODO:
1. Create assets directory under public (public/assets)
2. Move all files except index.html and main.css to assets folder
3. Change code to point at correct location of files (should only be in the index.html file, one reference in home.html)

Please make pull request to Hacktoberfest branch thanks!

**Comment by leogorman** [comment]
Working on this one now.
